/* Modelagem Basica 
ENTIDADE = TABELA
CAMPOS = ATRIBUTOS
*/

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)


/* PROCESSOS DE MODELAGEM */

/* FASE 01 E 02 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LOGICA - QUALQUER PROGRAM DE MODELAGEM

/* FASE 03 - DBA / AD */

MODELAGEM FISICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FISICA */

/* CRIANDO O BD */

CREATE DATABASE PROJETO;

/* CONECTAR AO BD */

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTES(
	NOME VARCHAR(30),
	CPF INT(10),
	EMAIL VARCHAR(30),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100),
	SEXO CHAR(1)

);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DA TABELA */

DESC CLIENTES;


/* sintaxe basica de inserção: INSERT INTO NOME DA TABELA... */

/* FORMA 1 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTES VALUES('JOAO', 988638273, 'JOAO@GMAIL.COM', '22923110', 'MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ', 'M'); 

INSERT INTO CLIENTES VALUES('CELIA', 541521456, 'CELIA@GMAIL.COM', '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ', 'F');

INSERT INTO CLIENTES VALUES('JORGE', 885755896, NULL, '58748895', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG', 'M');
							
/* FORMA 2 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTES(NOME, CPF, TELEFONE, ENDERECO, SEXO) VALUES('LILIAN', 887774856, '947785696', 'SENADOR SOARES = TIJUCA - RIO DE JANEIRO - RJ', 'F');

/* FORMA 3 - INSERT COMPACTO - SOMENTE MYSQL*/

INSERT INTO CLIENTES VALUES('ANA', 85548962, 'ANA@GLOBO.COM', '548556985', 'PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP', 'F'),
						   ('CARLA', 77458289, 'CARLA@TERATI.COM.BR', '66587458', 'SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG', 'F');
						   
/* COMANDO SELECT
seleção projeção e junção
*/

SELECT NOW() AS DATA_HORA, 'IGOR MORGADO' AS ALUNO;

SELECT NOME, EMAIL, SEXO FROM CLIENTES;

SELECT NOME, EMAIL, SEXO, NOW() AS DATA_HORA FROM CLIENTES;

SELECT * FROM CLIENTES;

/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, SEXO, CPF FROM CLIENTES WHERE SEXO = 'M';

/* USANDO O LIKE */

SELECT NOME, CPF FROM CLIENTES WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA % -> QUALQUER COISA ANTES DO QUE ESTOU SELECIONANDO */

SELECT NOME, CPF FROM CLIENTES WHERE ENDERECO LIKE '%RJ';


/* ATUALIZANDO INFORMAÇÕES */ 

UPDATE CLIENTES SET EMAIL = 'LILIAN@HOTMAIL.COM' WHERE NOME = 'LILIAN';


/* PRIMEIRA FORMA NORMAL 

1- TODO CAMPO VETORIZADO SE TORNA OUTRA TABELA 

2- TODO CAMPO MULTIVALORADO SE TORNA OUTRA TABELA

3- TODA TABELA NECESSITA DE UM CAMPO QUE IDENTIFIQUE TODO REGISTRO COMO UNICO
A CHAVE PRIMARIA OU PRIMERY KEY

*/



CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTES(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'CEL', 'COM') NOT NULL,
	NUMERO VARCHAR(15) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTES(IDCLIENTE)
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(20) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTES(IDCLIENTE)
);


INSERT INTO CLIENTES VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTES VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTES VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTES VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTES VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTES VALUES(NULL,'CELIA','F','CELIA@IG.COM','5767876889');

UPDATE CLIENTES SET EMAIL = 'CELIA@IG.COM', SEXO = 'F' WHERE NOME = 'CELIA';


/* EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGENIRA FICA NA TABELA MAIS FRACA
   EM RELACIONAMENTO 1 X N A CHAVE ESTRANGENIRA FICA NA TABELA N*/
   

SELECT NOME, SEXO, NUMERO
FROM CLIENTES
	INNER JOIN TELEFONE
	ON IDCLIENTE = ID_CLIENTE;
	
SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTES
	INNER JOIN TELEFONE
	ON IDCLIENTE = ID_CLIENTE
WHERE NUMERO LIKE '%6';

SELECT CLIENTES.NOME, CLIENTES.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTES
INNER JOIN ENDERECO
ON CLIENTES.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTES.IDCLIENTE = TELEFONE.ID_CLIENTE;

/* OU */

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTES C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;