CREATE DATABASE PROJETO_OFICINA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	TELEFONE VARCHAR(20)
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	NOMECARRO VARCHAR(20) NOT NULL
	MARCA VARCHAR(20) NOT NULL,
	ID_CLIENTE INT NOT NULL UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TINTA(
	IDTINTA INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(20),
	ID_CARRO INT NOT NULL,
	FOREIGN KEY(ID_CARRO)
	REFERENCES CARRO(IDCARRO)
);

INSERT INTO CLIENTE VALUES(NULL, 'IGOR MORGADO', '999323931');
INSERT INTO CLIENTE VALUES(NULL, 'ANA CLAUDIA', '99284468');
INSERT INTO CLIENTE VALUES(NULL, 'JOAO GUILHERME', '98645952');
INSERT INTO CLIENTE VALUES(NULL, 'PENHA HENRIQUE', '99567921');
INSERT INTO CLIENTE VALUES(NULL, 'ANTONIO NUNES', NULL);

INSERT INTO CARRO VALUES(NULL, 'CORSA', 'CHEVROLET', 1);
INSERT INTO CARRO VALUES(NULL, 'CELTA', 'CHEVROLET', 2);
INSERT INTO CARRO VALUES(NULL, 'UNO', 'FIAT', 3);
INSERT INTO CARRO VALUES(NULL, 'HB20', 'HYUNDAI', 4);
INSERT INTO CARRO VALUES(NULL, 'COROLA', 'TOYOTA', 5);

INSERT INTO TINTA VALUES(NULL, 'PRATA', 1);
INSERT INTO TINTA VALUES(NULL, 'PRETO', 2);
INSERT INTO TINTA VALUES(NULL, 'BRANCO', 3);
INSERT INTO TINTA VALUES(NULL, 'AZUL', 1);
INSERT INTO TINTA VALUES(NULL, 'VERMELHO', 5);
INSERT INTO TINTA VALUES(NULL, 'VERDE', 4);

SELECT P.NOME, C.NOMECARRO, T.COR FROM CLIENTE P
INNER JOIN CARRO C 
ON IDCLIENTE = ID_CLIENTE
INNER JOIN TINTA T  
ON IDCARRO = ID_CARRO
WHERE COR = 'PRATA'; 

SELECT P.NOME, C.NOMECARRO, T.COR FROM CLIENTE P
INNER JOIN CARRO C 
ON IDCLIENTE = ID_CLIENTE
INNER JOIN TINTA T  
ON IDCARRO = ID_CARRO
WHERE MARCA = 'CHEVROLET'; 

SELECT P.NOME, C.NOMECARRO, T.COR FROM CLIENTE P
INNER JOIN CARRO C 
ON IDCLIENTE = ID_CLIENTE
INNER JOIN TINTA T  
ON IDCARRO = ID_CARRO
WHERE NOMECARRO = 'HB20'; 
