CREATE DATABASE PROJETO_OFICINA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL,
	ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('CEL', 'RES', 'COM') NOT NULL,
	NUMERO VARCHAR(20) NOT NULL,
	ID_CLIENTE INT
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(20) NOT NULL,
	PLACA VARCHAR(20) NOT NULL UNIQUE,
	ID_MARCA INT
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(20) UNIQUE
);

CREATE TABLE COR_CARRO(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO, ID_COR)
);


/* CONSTRAINTS */

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);


ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);


ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);


ALTER TABLE COR_CARRO
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES COR(IDCOR);

ALTER TABLE COR_CARRO
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

INSERT INTO MARCA VALUES(NULL, 'CHEVROLET');
INSERT INTO MARCA VALUES(NULL, 'FIAT');
INSERT INTO MARCA VALUES(NULL, 'HYUNDAI');
INSERT INTO MARCA VALUES(NULL, 'TOYOTA');

INSERT INTO CARRO VALUES(NULL, 'CORSA', 'MTB1234', 1);
INSERT INTO CARRO VALUES(NULL, 'CELTA', 'ASD1234', 1);
INSERT INTO CARRO VALUES(NULL, 'UNO', 'GFT4556', 2);
INSERT INTO CARRO VALUES(NULL, 'HB20', 'THY4859', 3);
INSERT INTO CARRO VALUES(NULL, 'COROLA', 'KJH1231', 4);

INSERT INTO CLIENTE VALUES(NULL, 'IGOR MORGADO', 'M', 1);
INSERT INTO CLIENTE VALUES(NULL, 'ANA CLAUDIA', 'F', 2);
INSERT INTO CLIENTE VALUES(NULL, 'JOAO GUILHERME', 'M', 3);
INSERT INTO CLIENTE VALUES(NULL, 'PENHA HENRIQUE', 'F', 4);
INSERT INTO CLIENTE VALUES(NULL, 'ANTONIO NUNES', 'M', 5);

INSERT INTO TELEFONE VALUES(NULL, 'CEL', '999323931', 1);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '99284468', 2);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '98645952', 3);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '99567921', 4);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '98745631', 5);

INSERT INTO COR VALUES(NULL, 'PRATA');
INSERT INTO COR VALUES(NULL, 'PRETO');
INSERT INTO COR VALUES(NULL, 'BRANCO');
INSERT INTO COR VALUES(NULL, 'AZUL');
INSERT INTO COR VALUES(NULL, 'VERMELHO');
INSERT INTO COR VALUES(NULL, 'VERDE');

INSERT INTO COR_CARRO VALUES(1, 1);
INSERT INTO COR_CARRO VALUES(2, 2);
INSERT INTO COR_CARRO VALUES(3, 5);
INSERT INTO COR_CARRO VALUES(3, 2);
INSERT INTO COR_CARRO VALUES(4, 3);
INSERT INTO COR_CARRO VALUES(5, 6);


SELECT P.NOME, C.MODELO FROM CLIENTE P
INNER JOIN CARRO C 
ON P.ID_CARRO = C.IDCARRO; 
